server:
  port: 8080

spring:
  application:
    name: dsy1107-api-gateway-lab
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5500"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"

          default-filters:
            - AddResponseHeader=X-Gateway-Lab, DSY1107
          
          
          routes:
            # ETAPA INICIAL
            # Esta ruta ya funciona para que el grupo pueda comprobar
            # el concepto de route + integration antes de continuar.
            - id: posts-v1
              uri: https://jsonplaceholder.typicode.com
              predicates:
                - Path=/api/v1/posts/**
              filters:
                # El cliente invoca /api/v1/posts/1, pero el backend público
                # recibe /posts/1.
                - RewritePath=/api/v1/(?<segment>.*), /$\{segment}
                - AddResponseHeader=X-API-Version, v1


          # TODO ETAPA C:
          # Agregar una ruta posts-v2 y un header X-API-Version.
            - id: posts-v2
              uri: https://jsonplaceholder.typicode.com
              predicates:
                - Path=/api/v2/posts/**
              filters:
                - RewritePath=/api/v2/(?<segment>.*), /$\{segment}
                - AddResponseHeader=X-API-Version, v2

          # TODO ETAPA D:
          # Agregar un header transversal X-Gateway-Lab.

          # TODO ETAPA E:
          # Configurar CORS para el cliente web que se ejecutará en puerto 5500.
